extends: base.j2
language: fr
header_image: home-fr.png
default_block: post
sidebar:
    -
        name: PROGRAMME
        url: http://schedule2013.rmll.info/?lang=fr
    -
        name: REPAS DU %LIBRE%
        url: /fr/repas-du-libre.html
    -
        name: '%JURI% WORKSHOP'
        url: /fr/juri.html
    -
        name: 'CERTIFICATION %LPI%'
        url: /fr/lpi.html
    -
        name: '%RADIO% RMLL'
        url: https://radio.rmll.info


