---
extends: base.j2
default_block: post
header_image: home-en.png
language: en
sidebar:
    -
        name: PROGRAM
        url: http://schedule2013.rmll.info/?lang=en
    -
        name: '%LIBRE% DINNER'
        url: /en/libre-dinner.html
    -
        name: 'JURI %WORKSHOP%'
        url: /en/juri.html
    -
        name: '%LPI% CERTIFICATION'
        url: /en/lpi.html
    -
        name: '%RADIO% RMLL'
        url: https://radio.rmll.info
