language: nl
header_image: home-nl.png
sidebar:
    -
        name: 'PROGRAMMA'
        url: http://schedule2013.rmll.info/?lang=nl
    -
        name: '%LIBRE% AVONDMAAL'
        url: /nl/libre-avondmaal.html
    -
        name: 'JURI %WORKSHOP%'
        url: /nl/juri.html
    -
        name: '%LPI% CERTIFICATION'
        url: /nl/lpi.html
    -
        name: '%RADIO% RMLL'
        url: https://radio.rmll.info
